export const toolCategories = [
  {
    id: "calculator",
    name: "Calculators",
    toolsCreated: 20,
    totalUser: "150k+",
    posterImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/Calc-Tool-Main-Area-Card-Logo_s54bhl.jpg",
    dpImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/everydayCalcLogo_mu1ffq.webp",
    description: "Mathematical and financial calculations made easy",
  },
  {
    id: "converter",
    name: "Converters",
    toolsCreated: 20,
    totalUser: "150k+",
    posterImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/I_WANT_A_RUBEL_TO_BE_RUPEE_syu65p.png",
    dpImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/Your_paragraph_text_zcqwae.png",
    description: "Convert between different units and formats",
  },
  {
    id: "generator",
    name: "Generators",
    toolsCreated: 20,
    totalUser: "150k+",
    posterImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/BE_THE_GENERATOR_OF_SUCCESS_hxcxay.png",
    dpImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/ChatGPT_Image_Oct_20_2025_07_32_19_PM_gchdzh.png",
    description: "Generate passwords, codes, and unique identifiers",
  },
  {
    id: "miscellaneous",
    name: "Miscellaneous",
    toolsCreated: 20,
    totalUser: "150k+",
    posterImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/LET_S_DO_SOME_MISCELLANEOUS_rsxtso.png",
    dpImg:
      "https://res.cloudinary.com/dva4r5mad/image/upload/Add_the_text__MISCEL_pzoltc.png",
    description: "Additional utilities and helpful tools for additional use",
  },
];
export const toolsData = [
  // Calculators
  {
    id: 1,
    name: "Scientific Calculator",
    slug: "scientific-calculator",
    description: "Advanced mathematical calculations",
    icon: "🧮",
    category: "calculator",
    categoryName: "Calculator",
    categoryColor: "from-blue-400 to-blue-600",
    gradient: "from-blue-400 to-indigo-600",
    features: [
      "Trigonometric functions",
      "Logarithms",
      "Complex numbers",
      "History",
    ],
    isPopular: true,
  },
  {
    id: 2,
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentages quickly",
    icon: "💯",
    category: "calculator",
    categoryName: "Calculator",
    categoryColor: "from-blue-400 to-blue-600",
    gradient: "from-cyan-400 to-blue-600",
    features: [
      "Percentage of",
      "Percentage change",
      "Increase/Decrease",
      "Comparison",
    ],
    isPopular: true,
  },
  {
    id: 3,
    name: "BMI Calculator",
    slug: "bmi-calculator",
    description: "Calculate Body Mass Index",
    icon: "⚖️",
    category: "calculator",
    categoryName: "Calculator",
    categoryColor: "from-blue-400 to-blue-600",
    gradient: "from-teal-400 to-cyan-600",
    features: [
      "Metric & Imperial",
      "Health status",
      "Ideal weight",
      "BMI chart",
    ],
    isPopular: false,
  },
  {
    id: 4,
    name: "Loan Calculator",
    slug: "loan-calculator",
    description: "Calculate loan payments and interest",
    icon: "💰",
    category: "calculator",
    categoryName: "Calculator",
    categoryColor: "from-blue-400 to-blue-600",
    gradient: "from-green-400 to-emerald-600",
    features: [
      "EMI calculation",
      "Interest rates",
      "Amortization schedule",
      "Prepayment",
    ],
    isPopular: true,
  },
  {
    id: 5,
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate exact age and time differences",
    icon: "📅",
    category: "calculator",
    categoryName: "Calculator",
    categoryColor: "from-blue-400 to-blue-600",
    gradient: "from-purple-400 to-indigo-600",
    features: [
      "Years, months, days",
      "Next birthday",
      "Age difference",
      "Zodiac sign",
    ],
    isPopular: false,
  },

  // Converters
  {
    id: 6,
    name: "Unit Converter",
    slug: "unit-converter",
    description: "Convert between various units",
    icon: "📏",
    category: "converter",
    categoryName: "Converter",
    categoryColor: "from-green-400 to-green-600",
    gradient: "from-orange-400 to-red-600",
    features: ["Length", "Weight", "Temperature", "Volume"],
    isPopular: true,
  },
  {
    id: 7,
    name: "Currency Converter",
    slug: "currency-converter",
    description: "Real-time currency exchange rates",
    icon: "💱",
    category: "converter",
    categoryName: "Converter",
    categoryColor: "from-green-400 to-green-600",
    gradient: "from-yellow-400 to-orange-600",
    features: ["Live rates", "150+ currencies", "Historical data", "Favorites"],
    isPopular: true,
  },
  {
    id: 8,
    name: "Base64 Converter",
    slug: "base64-converter",
    description: "Encode and decode Base64",
    icon: "🔐",
    category: "converter",
    categoryName: "Converter",
    categoryColor: "from-green-400 to-green-600",
    gradient: "from-gray-400 to-gray-600",
    features: ["Text to Base64", "Base64 to text", "File support", "URL safe"],
    isPopular: false,
  },
  {
    id: 9,
    name: "Color Converter",
    slug: "color-converter",
    description: "Convert between color formats",
    icon: "🎨",
    category: "converter",
    categoryName: "Converter",
    categoryColor: "from-green-400 to-green-600",
    gradient: "from-pink-400 to-purple-600",
    features: [
      "HEX to RGB",
      "HSL support",
      "Color picker",
      "Palette generator",
    ],
    isPopular: true,
  },
  {
    id: 10,
    name: "JSON to CSV",
    slug: "json-csv-converter",
    description: "Convert JSON to CSV and vice versa",
    icon: "📊",
    category: "converter",
    categoryName: "Converter",
    categoryColor: "from-green-400 to-green-600",
    gradient: "from-blue-400 to-teal-600",
    features: ["Nested JSON", "Custom delimiter", "Preview", "Download"],
    isPopular: false,
  },

  // Generators
  {
    id: 11,
    name: "Password Generator",
    slug: "password-generator",
    description: "Create strong, secure passwords",
    icon: "🔒",
    category: "generator",
    categoryName: "Generator",
    categoryColor: "from-purple-400 to-purple-600",
    gradient: "from-indigo-400 to-purple-600",
    features: [
      "Custom length",
      "Character sets",
      "Strength meter",
      "Bulk generate",
    ],
    isPopular: true,
  },
  {
    id: 12,
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Generate QR codes for any data",
    icon: "📱",
    category: "generator",
    categoryName: "Generator",
    categoryColor: "from-purple-400 to-purple-600",
    gradient: "from-purple-400 to-pink-600",
    features: [
      "Text, URL, WiFi",
      "Custom colors",
      "Logo embed",
      "Download PNG/SVG",
    ],
    isPopular: true,
  },
  {
    id: 13,
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    description: "Generate placeholder text",
    icon: "📝",
    category: "generator",
    categoryName: "Generator",
    categoryColor: "from-purple-400 to-purple-600",
    gradient: "from-gray-400 to-gray-600",
    features: [
      "Words/Paragraphs",
      "HTML tags",
      "Custom length",
      "Copy to clipboard",
    ],
    isPopular: false,
  },
  {
    id: 14,
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate unique identifiers",
    icon: "🆔",
    category: "generator",
    categoryName: "Generator",
    categoryColor: "from-purple-400 to-purple-600",
    gradient: "from-cyan-400 to-blue-600",
    features: ["UUID v4", "Bulk generate", "Custom format", "Validation"],
    isPopular: false,
  },
  {
    id: 15,
    name: "Hash Generator",
    slug: "hash-generator",
    description: "Generate various hash types",
    icon: "#️⃣",
    category: "generator",
    categoryName: "Generator",
    categoryColor: "from-purple-400 to-purple-600",
    gradient: "from-red-400 to-orange-600",
    features: [
      "MD5, SHA-256",
      "HMAC support",
      "File hashing",
      "Compare hashes",
    ],
    isPopular: true,
  },
];
